name: "nerd_facts_dbt"
version: "1.0.0"
config-version: 2

profile: "nerd_facts_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nerd_facts_dbt:
    +materialized: view
