nerd_facts_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt_user
      password: 610femt!
      port: 5432
      dbname: nerd_facts
      schema: public  # dbt will store transformed models here
      threads: 4
